### PR TITLE
Update the manifest along with the upstream modifications

### PR DESCRIPTION
**Pull request by bilelmoussaoui**

### CODE REVIEW

**Comment by bilelmoussaoui** [comment]
bot, build

**Comment by bilelmoussaoui** [comment]
@fosero The build fails here. I'm not sure how you were able to build totem-pl-parser without gmime in the upstream manifest of GNOME Music? 
It's the reason why the build fails here and it's not included in the runtime of GNOME

**Comment by bilelmoussaoui** [comment]
bot, build

**Comment by fosero** [comment]
@bilelmoussaoui totem-pl-parser from master dropped the gmime dep.

**Comment by bilelmoussaoui** [comment]
@fosero It's not needed by GNOME Music anyway? So, I can disable it here from totem-pl-parser and remove the gmime dependency

**Comment by fosero** [comment]
No it's not. Actually totem-pl-parser we don't even use anymore (we disable all on-disk playlists being shown). So that's one to fix upstream as well.

**Comment by bilelmoussaoui** [comment]
bot, build

**Comment by bilelmoussaoui** [comment]
Perfect! Removed gmime from here. Will update according to the newer dependencies on the next release of GNOME Music. For now, do you agree with the modifications on this PR?

**Pull request merged**
