### PR TITLE
Upgrade runtime to 3.32

### PR DESCRIPTION
**Pull request by tallero**

### CODE REVIEW

**Comment by fosero** [comment]
This only updates the platform, not the application itself.

**Comment by tallero** [comment]
@fosero I know, but if not upgraded in time people will have the old runtime installed just for this and some other program.

**Comment by Exalm** [comment]
Any problems with updating the app itself? If it's because https://gitlab.gnome.org/GNOME/gnome-music/tree/wip/mschraal/3-32-flatpak-stable-runtime doesn't pass CI, then it's because https://gitlab.gnome.org/GNOME/gnome-music/blob/wip/mschraal/3-32-flatpak-stable-runtime/.gitlab-ci.yml#L1 hasn't been changed to 3.32.

**Comment by tallero** [comment]
The flatpak test build is working for me. Do not know about CI.

**Comment by Exalm** [comment]
See https://github.com/flathub/org.gnome.Music/pull/8

**Comment by fosero** [comment]
@Exalm Thanks for helping out, missed that part :+1:

**Comment by tallero** [comment]
@Exalm Sorry, I did not know a new release of music itself came out.

**Pull request closed without merging**
