### PR TITLE
Add x-data-checker

### PR DESCRIPTION
**Pull request by A6GibKm**
Will automatically open PRs only when there is new release of Music.

### CODE REVIEW

**Comment by ptitjano** [comment]
Thank you @A6GibKm 
Is there is a way to test this change works ?

**Comment by alatiera** [comment]
@ptitjano check the comment above from the bot!

https://github.com/flathub/org.gnome.Music/pull/39#issuecomment-1342613896

**Comment by alatiera** [comment]
oh, If you meant about the update bot, not sure about that one but the changes look good overall

**Comment by ptitjano** [comment]
Let's go !

Thanks

**Comment by A6GibKm** [comment]
No idea how to test, we will know once there is a release of one of the marked modules

**Pull request merged**
